### ISSUE TITLE
getting errors when eve app is requesting data

### ISSUE THREAD

**Issue by eshaka** [skrollme/homebridge-eveatmo#13]
at process._tickCallback (internal/process/next_tick.js:180:9)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at endReadableNT (_stream_readable.js:1055:12)
    at IncomingMessage.emit (events.js:208:7)
    at emitNone (events.js:106:13)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)
    at HAPServer.emit (events.js:224:7)
    at emitMany (events.js:147:13)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:720:8)
    at Array.forEach (<anonymous>)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:756:20)
    at S2R2Characteristic.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:162:10)
    at S2R2Characteristic.emit (events.js:217:7)
    at emitThree (events.js:136:13)
    at FakeGatoHistory.getCurrentS2R2 (/usr/local/lib/node_modules/homebridge-eveatmo/node_modules/fakegato-history/fakegato-history.js:700:56)
TypeError: Cannot read property 'time' of null
						                                                 ^
						numToHex(swap32(this.history[this.memoryAddress].time - this.refTime - EPOCH_OFFSET), 8),

**Comment by skrollme** [comment]
This message comes from _homebridge-eveatmo_'s dependency [fakegato-history](https://github.com/simont77/fakegato-history)
