### ISSUE TITLE
homebridge crashes on 0.4.2

### ISSUE THREAD

**Issue by hronix** [skrollme/homebridge-eveatmo#23]
I'm testing 0.4.2 for a week and experience crashes about every 48 hours. 
Last crash: [1/8/2019, 11:25:47 AM]
Previous: [1/6/2019, 1:59:46 AM]
Before: [1/5/2019, 12:22:05 AM]

Problems are the same, here is last dump

[1/8/2019, 11:25:47 AM] [eveatmo platform] Loading new data from API for: weatherstation
buffer.js:750
        return this.hexWrite(string, offset, length);
                    ^

TypeError: Invalid hex string
    at TypeError (native)
    at Buffer.write (buffer.js:750:21)
    at fromString (buffer.js:203:26)
    at Function.Buffer.from (buffer.js:99:12)
    at new Buffer (buffer.js:80:17)
    at EveatmoWeatherPressureService.hexToBase64 (/volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/service/eveatmo-weather-pressure.js:97:11)
    at EveatmoWeatherPressureService.updateCharacteristics (/volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/service/eveatmo-weather-pressure.js:117:23)
    at /volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:150:51
    at Array.forEach (native)
    at EveatmoWeatherAccessory.applyWeatherData (/volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:148:24)
    at EveatmoWeatherAccessory.notifyUpdate (/volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:99:9)
    at WeatherstationDeviceType.<anonymous> (/volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/device/weatherstation-device.js:47:18)
    at Array.forEach (native)
    at WeatherstationDeviceType.<anonymous> (/volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/device/weatherstation-device.js:46:24)
    at netatmo.<anonymous> (/volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/node_modules/netatmo/netatmo.js:227:14)
    at Request.self.callback (/volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/volume1/home/stas/.npm-global/lib/node_modules/homebridge-eveatmo/node_modules/request/request.js:1083:12)

**Comment by skrollme** [comment]
I looked a little bit into this and I have no idea how this error can happen and this part of the code. There are some converting functions before which should return consistent values/datatypes.

Which node version do you use on which platform?

**Comment by hronix** [comment]
@skrollme Had it again. May be there is problem in other home bridge plugins which I use? 
Platform: Linux hronixNAS 3.4.26 #1 SMP PREEMPT Fri Nov 23 03:32:01 CST 2018 i686 GNU/Linux
Node: v6.9.1

**Comment by hronix** [comment]
Okay, I will try. But I can report my testing results so far. I disabled homebridge-eveatmo plugin for 1 month and everything works just fine, no problems or crashes. So I'm going enable it again and disable other one by one.
