### ISSUE TITLE
Invalid hex string | homebridge stopped working EveatmoWeatherPressureService ??

### ISSUE THREAD

**Issue by DJay-X** [skrollme/homebridge-eveatmo#8]
Hope you can help. Is again the Netatmo API/Server the problem?
Homebridge stopped working out of the blue with the error shown below.

Any chance to see this in the near future? At the moment everything at home stopped just because of the plugin. Don't get me wrong, I love this plugin and desperately see development going on.

Thanks a lot for the help and reply.

```
Okt 01 08:55:33 raspberrypi homebridge[2945]: TypeError: Invalid hex string
Okt 01 08:55:33 raspberrypi homebridge[2945]: at Buffer.write (buffer.js:805:21)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at fromString (buffer.js:212:18)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at Function.Buffer.from (buffer.js:104:12)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at new Buffer (buffer.js:85:17)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at EveatmoWeatherPressureService.hexToBase64 (/usr/local/lib/node_modules/homebridge-eveatmo/service/eveatmo-weather-pressure.js:97:11)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at EveatmoWeatherPressureService.updateCharacteristics (/usr/local/lib/node_modules/homebridge-eveatmo/service/eveatmo-weather-pressure.js:117:23)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at /usr/local/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:166:51
Okt 01 08:55:33 raspberrypi homebridge[2945]: at Array.forEach (native)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at EveatmoWeatherAccessory.applyWeatherData (/usr/local/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:164:24)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at EveatmoWeatherAccessory.notifyUpdate (/usr/local/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:100:9)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at EveatmoWeatherAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:83:11)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at WeatherstationDeviceType.<anonymous> (/usr/local/lib/node_modules/homebridge-eveatmo/lib/netatmo-device.js:75:6)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at NodeCache.module.exports.NodeCache.get (/usr/local/lib/node_modules/homebridge-eveatmo/node_modules/node-cache/lib/node_cache.js:90:11)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at NodeCache.get (/usr/local/lib/node_modules/homebridge-eveatmo/node_modules/node-cache/lib/node_cache.js:12:59)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at WeatherstationDeviceType.refreshDeviceData (/usr/local/lib/node_modules/homebridge-eveatmo/lib/netatmo-device.js:66:14)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at EveatmoWeatherAccessory.refreshData (/usr/local/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:81:16)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at new EveatmoWeatherAccessory (/usr/local/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:46:9)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at WeatherstationDeviceType.buildAccessory (/usr/local/lib/node_modules/homebridge-eveatmo/device/weatherstation-device.js:59:12)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at WeatherstationDeviceType.<anonymous> (/usr/local/lib/node_modules/homebridge-eveatmo/lib/netatmo-device.js:108:26)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at Array.forEach (native)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at WeatherstationDeviceType.buildAccessories (/usr/local/lib/node_modules/homebridge-eveatmo/lib/netatmo-device.js:95:32)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at WeatherstationDeviceType.<anonymous> (/usr/local/lib/node_modules/homebridge-eveatmo/lib/netatmo-device.js:57:10)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at WeatherstationDeviceType.<anonymous> (/usr/local/lib/node_modules/homebridge-eveatmo/lib/netatmo-device.js:71:7)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at WeatherstationDeviceType.<anonymous> (/usr/local/lib/node_modules/homebridge-eveatmo/device/weatherstation-device.js:49:5)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at netatmo.<anonymous> (/usr/local/lib/node_modules/homebridge-eveatmo/node_modules/netatmo/netatmo.js:227:14)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at Request.self.callback (/usr/local/lib/node_modules/homebridge-eveatmo/node_modules/request/request.js:186:22)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at emitTwo (events.js:106:13)
Okt 01 08:55:33 raspberrypi homebridge[2945]: at Request.emit (events.js:194:7)
```

**Comment by DJay79** [comment]
If the Netatmo server makes a mistake and you are just restarting the homebridge, then the start doesn't run clean and the homebridge gets stuck.
There should be a timeout that the start of the homebridge continues and the other plugins at least run.

Any chance to see this in the near future? At the moment everything at home stopped just because of the plugin. Don't get me wrong, I love this plugin and desperately see development going on.

Thanks

**Comment by skrollme** [comment]
Hello @DJay79 , most parts of the base code were copied from the homebridge-netatmo plugin so I have to dig in a little deeper to check this out. I also had the problem that errors on the API side block/freeze the rest of the homebridge, but I did not get a good start to overhaul the plugins structure because the plugin build its accessory structure (modules/sensors) directly from the netatmo API-response.
But at the moment I'm not planning to refactor this part of the plugin. My next goal is to make progress on the history-feature.

**Comment by DJay79** [comment]
Thanks for your reply and your ongoing work. 
I think a lot of people love your Plugin. Especially of course the German fans on http://forum.smartapfel.de/forum/ 😉

If there is anything I or we can do to help investigate or test, please of course let me know here or there. with a heavy heart I had to uninstall and remove it from my config today to keep Homebridge running. :(

**Comment by skrollme** [comment]
I took a look at it yesterday and it seems hard for the plugin to detect problems with the API in the current structure because of some error-handling decisions in the underlying netatmo-library. I already wrote to the author and asked him about this. See: https://github.com/karbassi/netatmo/issues/36

**Comment by r32er** [comment]
I got the same error.

**Comment by skrollme** [comment]
I close this because there were no more posts in the recent time
